# dbt profile configuration for healthcare ETL pipeline
# This file should be placed in ~/.dbt/ directory or in the project root

healthcare_etl:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'localhost') }}"
      port: "{{ env_var('POSTGRES_PORT', '5433') | int }}"
      user: "{{ env_var('POSTGRES_USER', 'etl_user') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', 'etl_password') }}"
      dbname: "{{ env_var('POSTGRES_DB', 'healthcare_warehouse') }}"
      schema: public
      threads: 4
      keepalives_idle: 0
      connect_timeout: 10
      
    prod:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST') }}"
      port: "{{ env_var('POSTGRES_PORT') | int }}"
      user: "{{ env_var('POSTGRES_USER') }}"
      password: "{{ env_var('POSTGRES_PASSWORD') }}"
      dbname: "{{ env_var('POSTGRES_DB') }}"
      schema: public
      threads: 8
      keepalives_idle: 0
      connect_timeout: 10
